# part2 :deployment
## test local build
GET https://{{host}}/ping
Accept: application/json

### test users
GET https://{{host}}/users
Accept: application/json

### added user
POST https://{{host}}/users
Content-Type: application/json

{
  "username": "hello",
  "email": "hello@world.com"
}


### get users
GET https://{{host}}/users
Accept: application/json

### get single user
GET https://{{host}}/users/1
Accept: application/json

### POST a user
POST https://{{host}}/users
Content-Type: application/json

{
  "username": "someone",
  "email": "someone@something.com"
}

### Update a user
PUT https://{{host}}/users/4
Content-Type: application/json

{
  "username": "foo",
  "email": "foo@something.com"
}


### Update a user
DELETE https://{{host}}/users/4
Accept: application/json
